### ISSUE TITLE
convert from PropertySet to Property

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/optics-lab#7] opened 2016-12-06 23:08 UTC
PropertySet is deprecated and should be replaced by Property, see phetsims/axon#102. Since this sim hasn't published yet, this should be done before RC testing and publishing.

**Comment by veillette** [comment] 2017-06-29 14:29
We should address all the assertions that are currently being triggered before performing the conversion to Property ( #9, #11, #13, #14)

**Comment by veillette** [comment] 2017-07-02 15:48
I forgot to tag this commit: https://github.com/phetsims/optics-lab/commit/6c3030f100f2a7792bda8508d8b0542a07e7d28c

**Comment by veillette** [comment] 2017-07-02 15:55
I addressed the assertions, except for #9. Since I was able to reproduce how to trigger this assertion, I was able to work around it and do the conversion to PropertySet.

The simulation is currently lacking a reset all button but reset functions were added to reset the properties.

The reset issue is tracked in #20

**Comment by veillette** [comment] 2017-07-03 22:42
Work done. Closing

**Closed by veillette** 2017-07-03 22:42 UTC
