### ISSUE TITLE
CT: max must be >= min

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/optics-lab#24] opened 2018-10-31 15:57 UTC
This CT error has been occurring for days, surprised that no one created an issue.

@chrisklus might this be causing https://github.com/phetsims/dot/issues/80?

optics-lab : fuzz : require.js : load
Uncaught Error: Assertion failed: max must be >= min. min: -100, max: -800
Error: Assertion failed: max must be >= min. min: -100, max: -800
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/assert/js/assert.js:22:13)
    at new Range (https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/dot/js/Range.js?bust=1541000066861:22:15)
    at new ControlPanel (https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/optics-lab/js/optics-lab/view/ControlPanel.js?bust=1541000066861:159:70)
    at new ControlPanelManager (https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/optics-lab/js/optics-lab/view/ControlPanelManager.js?bust=1541000066861:68:29)
    at new OpticsLabScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/optics-lab/js/optics-lab/view/OpticsLabScreenView.js?bust=1541000066861:42:32)
    at OpticsLabScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/optics-lab/js/optics-lab/OpticsLabScreen.js?bust=1541000066861:26:34)
    at OpticsLabScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/joist/js/Screen.js?bust=1541000066861:251:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/joist/js/Sim.js?bust=1541000066861:783:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/joist/js/Sim.js?bust=1541000066861:791:27
id: Bayes Chrome
Approximately 10/31/2018, 8:50:25 AM
optics-lab : fuzz : require.js : run
Uncaught Error: Assertion failed: max must be >= min. min: -100, max: -800
Error: Assertion failed: max must be >= min. min: -100, max: -800
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/assert/js/assert.js:22:13)
    at new Range (https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/dot/js/Range.js?bust=1541000066861:22:15)
    at new ControlPanel (https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/optics-lab/js/optics-lab/view/ControlPanel.js?bust=1541000066861:159:70)
    at new ControlPanelManager (https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/optics-lab/js/optics-lab/view/ControlPanelManager.js?bust=1541000066861:68:29)
    at new OpticsLabScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/optics-lab/js/optics-lab/view/OpticsLabScreenView.js?bust=1541000066861:42:32)
    at OpticsLabScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/optics-lab/js/optics-lab/OpticsLabScreen.js?bust=1541000066861:26:34)
    at OpticsLabScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/joist/js/Screen.js?bust=1541000066861:251:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/joist/js/Sim.js?bust=1541000066861:783:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1540997425120/joist/js/Sim.js?bust=1541000066861:791:27
id: Bayes Chrome
Approximately 10/31/2018, 8:50:25 AM

**Comment by chrisklus** [comment] 2018-10-31 23:01
>@chrisklus might this be causing phetsims/dot#80?

This is indeed a result of the changes in that issue. 

This issue is a second duplicate of https://github.com/phetsims/optics-lab/issues/22, closing.

**Closed by chrisklus** 2018-10-31 23:01 UTC
Labels: type:automated-testing, type:bug
