### ISSUE TITLE
CT: Max must be >= min

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/optics-lab#23] opened 2018-10-25 21:39 UTC
```
optics-lab : fuzz : require.js : load
Uncaught Error: Assertion failed: max must be >= min. min: -100, max: -800
Error: Assertion failed: max must be >= min. min: -100, max: -800
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/assert/js/assert.js:22:13)
    at new Range (https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/dot/js/Range.js?bust=1540500918055:22:15)
    at new ControlPanel (https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/optics-lab/js/optics-lab/view/ControlPanel.js?bust=1540500918055:159:70)
    at new ControlPanelManager (https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/optics-lab/js/optics-lab/view/ControlPanelManager.js?bust=1540500918055:68:29)
    at new OpticsLabScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/optics-lab/js/optics-lab/view/OpticsLabScreenView.js?bust=1540500918055:42:32)
    at OpticsLabScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/optics-lab/js/optics-lab/OpticsLabScreen.js?bust=1540500918055:26:34)
    at OpticsLabScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/joist/js/Screen.js?bust=1540500918055:251:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/joist/js/Sim.js?bust=1540500918055:783:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/joist/js/Sim.js?bust=1540500918055:791:27
id: Bayes Chrome
Approximately 10/25/2018, 2:39:27 PM
optics-lab : fuzz : require.js : run
Uncaught Error: Assertion failed: max must be >= min. min: -100, max: -800
Error: Assertion failed: max must be >= min. min: -100, max: -800
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/assert/js/assert.js:22:13)
    at new Range (https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/dot/js/Range.js?bust=1540500918055:22:15)
    at new ControlPanel (https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/optics-lab/js/optics-lab/view/ControlPanel.js?bust=1540500918055:159:70)
    at new ControlPanelManager (https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/optics-lab/js/optics-lab/view/ControlPanelManager.js?bust=1540500918055:68:29)
    at new OpticsLabScreenView (https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/optics-lab/js/optics-lab/view/OpticsLabScreenView.js?bust=1540500918055:42:32)
    at OpticsLabScreen.Screen.call.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/optics-lab/js/optics-lab/OpticsLabScreen.js?bust=1540500918055:26:34)
    at OpticsLabScreen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/joist/js/Screen.js?bust=1540500918055:251:25)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/joist/js/Sim.js?bust=1540500918055:783:18)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1540499967370/joist/js/Sim.js?bust=1540500918055:791:27
id: Bayes Chrome
Approximately 10/25/2018, 2:39:27 PM
```

**Comment by chrisklus** [comment] 2018-10-25 21:42
Duplicate of https://github.com/phetsims/optics-lab/issues/22, closing.

**Closed by chrisklus** 2018-10-25 21:42 UTC
Labels: type:automated-testing
